import { request } from 'src/request';

export function getTotalRebate() {
  return request.get<any, number>('/rebate/getTotalRebate');
}

export function getRebateDetail(params?: { page?: number; size?: number }) {
  return request.get<any, RebateDetailResponse>('/rebate/getInviteRebateDetail', { params });
}

export function applyWithdraw(amount: number, wechatAccount?: string) {
  return request.post<any, string>('/rebate/applyWithdraw', { amount, wechatAccount });
}

export function getWithdrawRecords(params?: { page?: number; size?: number }) {
  return request.get<any, WithdrawRecordResponse>('/rebate/getWithdrawRecords', { params });
}

// Generated by https://quicktype.io

export interface RebateDetailResponse {
  content: RebateDetail[];
  totalElements: number;
}

export interface RebateDetail {
  inviter_name: string;
  order_no: string;
  withdraw_id: number | null;
  withdraw_status?: string;
  update_time: number;
  rebate_change: number;
  create_time: number;
  change_type: number; // 0-获取返利, 1-提现支出
  invitee_name: string;
}

export interface WithdrawRecordResponse {
  content: WithdrawRecord[];
  totalElements: number;
}

export interface WithdrawRecord {
  id: number;
  amount: number;
  wechatAccount?: string;
  status: string;
  remark: string;
  create_time: number;
  update_time: number;
}
