import { request } from 'src/request';

export function getTotalRebate() {
  return request.get<any, number>('/rebate/getTotalRebate');
}

export function getRebateDetail() {
  return request.get<any, RebateDetailResponse>('/rebate/getInviteRebateDetail');
}
// Generated by https://quicktype.io

export interface RebateDetailResponse {
  content: RebateDetail[];
  totalElements: number;
}

export interface RebateDetail {
  inviter_name: string;
  order_no: string;
  withdraw_id: null;
  update_time: number;
  rebate_change: number;
  create_time: number;
  change_type: number;
  invitee_name: string;
}
